# Generated by Django 5.1.3 on 2024-11-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_notadeprioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='notadeprioridade',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notes',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
