# Generated by Django 5.1.3 on 2024-11-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_notadeprioridade_completed_notes_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notadeprioridade',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='notes',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
