# Generated by Django 5.1.3 on 2024-11-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_notadeprioridade_color_notes_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotadePrioridade',
        ),
        migrations.AddField(
            model_name='notes',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='prioridade não definida', max_length=6),
        ),
    ]
